name: GitHub Actions Demo

on: 
  push: 
   branches: [ main ]
   paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: 


jobs:
  Build: 
    runs-on:  ubuntu-latest
    steps:
      - name: List repo and branch details
        run: |
          echo " The job was triggered by an event: ${{ github.event_name }}"
          echo " The name of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
          tree
      - uses: actions/checkout@v4.2.2
      - name:  List files that exist in this repo
        run: |
          echo "The repository $ {{ github.repository }} contain the following files: "
          tree
