name: Reuse our other workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Who do you want to greet: '
        type: string
        required: true

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "${{ inputs.greeting }}"
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
